# -*- encoding: utf-8 -*-
##############################################################################
#
# Copyright (c) 2020 Taliform Inc.
#
# Author: Joshua <joshua@taliform.com>
#
# WARNING: This program as such is intended to be used by professional
# programmers who take the whole responsibility of assessing all potential
# consequences resulting from its eventual inadequacies and bugs
#
# This program is Free Software; you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
##############################################################################
from odoo import api, fields, models
from odoo.exceptions import ValidationError


class AccountBillingStatement(models.Model):
    _name = 'account.billing.statement'
    _description = 'Account Billing Statement'

    date_generated = fields.Date(string='Date Generated')
    generated_by = fields.Many2one('res.users', string='Generated By')
    billing_statement = fields.Binary(string='Billing Statement')
    invoice_id = fields.Many2one('account.move', string='Invoice', required=True)
    hash_code = fields.Char('Hash Code (MD5)')

    def name_get(self):
        result = []
        for rec in self:
            result.append((rec.id, "Billing Statement %s" % (rec.invoice_id.name,)))
        return result
